#!/bin/bash
#PBS -P oj47
#PBS -l ncpus=8
#PBS -l mem=100GB
#PBS -l walltime=24:00:00
#PBS -l storage=scratch/hm82

module load bwa
module load R/3.6.1
module load samtools
echo "Time: $(date). Begin structural PON assembly." >> $projectDir/DNAlog.txt

assemblyPath=$projectDir/assembled/PONassembly.bam
SVpath=$projectDir/structuralVariants/HeadNeckAllHealthy.vcf.gz
labelString=${labelString// /,}

/home/562/ds6924/software/gridss.sh --steps Assemble --jvmheap 90g --configuration /home/562/ds6924/software/gridss.properties --reference /scratch/hm82/Reference/hs38DH.fasta --output $SVpath --assembly $assemblyPath --threads 8 --jar /home/562/ds6924/software/gridss.jar --workingdir /scratch/hm82/temporary/ --blacklist /home/562/ds6924/databases/ENCFF419RSJ.bed --labels $labelString $inputString

echo "Time: $(date). End structural PON assembly." >> $projectDir/DNAlog.txt
