#!/bin/bash
#PBS -P hm82
#PBS -l ncpus=1
#PBS -l mem=20GB
#PBS -l walltime=2:00:00

module load bwa
module load samtools
SVfolder=/scratch/hm82/TCGA/structuralVariants/
SVfiles=$(find $SVfolder -name \*structural.vcf.gz)
SVfilesText=${SVfiles//\/scratch/INPUT=\/scratch}

echo "Time: $(date). Begin structural PON BEDPE creation." >> $projectDir/DNAlog.txt

java -Xmx16g -cp /home/562/ds6924/software/gridss.jar gridss.GeneratePonBedpe THREADS=1 NORMAL_ORDINAL=0 $SVfilesText REFERENCE_SEQUENCE=/scratch/hm82/Reference/hs38DH.fasta OUTPUT_BED=$SVfolder/patientNormals.bed OUTPUT_BEDPE=$SVfolder/patientNormals.bedpe

echo "Time: $(date). End structural PON BEDPE creation." >> $projectDir/DNAlog.txt
