#!/bin/bash

#PBS -l ncpus=4
#PBS -l mem=64GB
#PBS -l walltime=8:00:00

module load R/3.6.0
module load java
module load kraken2
module load blast
module load repeatmasker
GRIDSS_JAR=~/software/testing/gridss/target/gridss-2.10.0-gridss-jar-with-dependencies.jar

SVpath=$projectDir/structuralVariants/${outputID}structural.vcf.gz # Replace mapped directory by variants directory in path.
retroSVpath=${SVpath/.vcf.gz/AnnotatedRetro.vcf.gz} # Annotated with Retrotransposons.
retroViralSVpath=${retroSVpath/AnnotatedRetro/AnnotatedRetroViral} # Annotated with Viruses.

echo "Time: $(date). Begin structural variant filtering and annotation for $outputID" >> $projectDir/DNAlog.txt
~/software/testing/gridss/scripts/gridss_annotate_vcf_repeatmasker.sh -o $retroSVpath -j ~/software/testing/gridss/target/gridss-2.10.0-gridss-jar-with-dependencies.jar -t 4 -w /tmp/ $SVpath
~/software/testing/gridss/scripts/gridss_annotate_vcf_kraken2.sh -j $GRIDSS_JAR -t 4 --kraken2db /project/HeadNeck/databases/viralForKraken --output $retroViralSVpath $retroSVpath

rm $retroSVpath
echo "Time $(date). Complete structural variant filtering and annotation for $outputID." >> $projectDir/DNAlog.txt
