#!/bin/bash
#PBS -l select=1:ncpus=8:mem=100GB
#PBS -l walltime=20:00:00

module load bwa
module load htslib
module load samtools
module load R/3.6.0

temporaryDir=${projectDir/project/scratch/}
assemblyPath=$temporaryDir/assembled/${outputID}assembly.bam
SVpath=$projectDir/structuralVariants/${outputID}structural.vcf.gz # Replace mapped directory by variants directory in path.
retroSVpath=${SVpath/.vcf.gz/AnnotatedRetro.vcf} # Annotated with Retrotransposons.
retroViralSVpath=${retroSVpath/.vcf/Viral.vcf} # Annotated with Viruses.
somaticSVpath=${retroViralSVpath/.vcf/Somatic.vcf.bgz} # Final somatic file.
labelString=${labelString// /,}

if [ $genome == "hg19" ]
then
  blacklist=/project/HeadNeck/problemRegions/hg19/consensusBlacklistNoChr.bed
  BSgenome=BSgenome.Hsapiens.UCSC.hg19
  if [ $centre == "Broad" ]
  then
    FASTA=/project/HeadNeck/indexes/bwa/hg19/Homo_sapiens_assembly19.fasta
  else # Baylor
    FASTA=/project/HeadNeck/indexes/bwa/hg19/GRCh37-lite.fa
  fi
else # hg38
  FASTA=/project/HeadNeck/indexes/bwa/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
  blacklist=/project/HeadNeck/problemRegions/hg38/ENCFF419RSJ.bed
  BSgenome=BSgenome.Hsapiens.UCSC.hg38
fi

echo "Time: $(date). Begin structural variant detection for $outputID." >> $projectDir/DNAlog.txt
/home/dstr7320/software/gridss.sh --reference $FASTA --output $SVpath --assembly $assemblyPath --threads 8 --jar /home/dstr7320/software/gridss-2.6.3.jar --workingdir $temporaryDir --jvmheap 72g --blacklist $blacklist --labels $labelString $inputString
Rscript /home/dstr7320/software/gridss_annotate_insertions_repeatmaster.R --input $SVpath --output $retroSVpath --repeatmasker /project/HeadNeck/databases/hg38/RepeatMaskerDNAhg38.fa.out.gz --scriptdir /home/dstr7320/software/
java -Xmx12g -cp /home/dstr7320/software/gridss-2.6.3.jar gridss.AnnotateUntemplatedSequence REFERENCE_SEQUENCE=/project/HeadNeck/sequence/human_virus.fa INPUT=$retroSVpath.bgz OUTPUT=$retroViralSVpath.bgz
#bgzip -c $retroViralSVpath > $retroViralSVpath.bgz
#tabix -p vcf $retroViralSVpath.bgz
#rm $retroViralSVpath
#Rscript /home/dstr7320/software/gridss_somatic_filter.R --pondir $projectDir/structuralVariants/ --ref $BSgenome --input $retroViralSVpath.bgz --output ${retroViralSVpath/.vcf/Somatic.vcf} --scriptdir /home/dstr7320/software/
echo "Time: $(date). Complete structural variant detection for $outputID." >> $projectDir/DNAlog.txt


